[package]
name = "mif_tree_hash_derive"
version = "0.1.0"
authors = ["Faustas Butkus <faustas.butkus@gmail.com>"]
edition = "2018"

[lib]
name = "tree_hash_derive"
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
