[package]
name = "mif_ssz"
version = "0.1.0"
authors = ["Faustas Butkus <faustas.butkus@gmail.com>"]
edition = "2018"

[lib]
name = "ssz"

[dev-dependencies]
mif_ssz_derive = { path = "../mif_ssz_derive" }

[dependencies]
ethereum-types = "0.6"