[package]
name = "mif_tree_hash"
version = "0.1.0"
authors = ["Faustas Butkus <faustas.butkus@gmail.com>"]
edition = "2018"

[lib]
name = "tree_hash"

[dependencies]
eth2_hashing = "0.1"
lazy_static = "1.4"
